### ISSUE TITLE
Finish Writing all the DAO

### ISSUE THREAD

**Issue by Yichi-liu** [BookCooper/TheBookCooper#4]
I have written the user data access object. We still need more DAO for our tables (Should need 1 DAO for each of our tables) 

bookInfoDAO (done)
bookListingDAO (done)
bookSearchesDAO
bookTagsDAO
bookTransactionsDAO
pointTransactionsDAO
storeDAO
usersDAO (done)

**Comment by Aidan4478D** [comment]
I'll work on the bookInfoDAO
